export const work = [
  {
    id: 1,
    responsive: "responsive",
    title: "E-commerce Shopping cart",
    youtubeLink: "https://youtu.be/Ry2P6BuwboE",
    demo: null,
    github: "https://github.com/Mo-khalifa2002/new-shop.git",
    img: "https://images.pexels.com/photos/296916/pexels-photo-296916.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,
    responsive: "responsive",
    title: "restaurant landing page",
    youtubeLink: "https://youtu.be/AL2OB9vMRuo",
    demo: null,
    github: null,
    img: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    responsive: "responsive",
    title: "food recipe search",
    demo: "https://mo-khalifa-recipe.netlify.app/",
    youtubeLink: "https://youtu.be/hifnmHaw2UM",
    github: "https://github.com/Mo-khalifa2002/recipe.git",
    img: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    responsive: "responsive",
    title: "Portfolio",
    demo: null,
    youtubeLink: "https://youtu.be/hifnmHaw2UM",
    github: "https://github.com/Mo-khalifa2002/portofolio_project.git",
    img: "https://images.pexels.com/photos/8100514/pexels-photo-8100514.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    responsive: "responsive",
    title: "to-do app",
    demo: "https://mo-khalifa-todo-app.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/todo-reactjs-app.git",
    img: "https://images.pexels.com/photos/110473/pexels-photo-110473.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    responsive: "not responsive",
    title: "Movies - only focusing on react js",
    demo: "https://mo-khalifa-movies.netlify.app/",
    youtubeLink: "https://youtu.be/T2jzC3OzcIs",
    github: "https://github.com/Mo-khalifa2002/movies.git",
    img: "https://images.pexels.com/photos/65437/pexels-photo-65437.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];


export const moreWork = [
  {
    id: 1,
    responsive: "responsive",
    title: "E-commerce Shopping cart",
    youtubeLink: "https://youtu.be/Ry2P6BuwboE",
    demo: null,
    github: "https://github.com/Mo-khalifa2002/new-shop.git",
    img: "https://images.pexels.com/photos/296916/pexels-photo-296916.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 2,
    responsive: "responsive",
    title: "restaurant landing page",
    youtubeLink: "https://youtu.be/AL2OB9vMRuo",
    demo: null,
    github: null,
    img: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    responsive: "responsive",
    title: "food recipe search",
    demo: "https://mo-khalifa-recipe.netlify.app/",
    youtubeLink: "https://youtu.be/hifnmHaw2UM",
    github: "https://github.com/Mo-khalifa2002/recipe.git",
    img: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    responsive: "responsive",
    title: "Portfolio",
    demo: null,
    youtubeLink: "https://youtu.be/hifnmHaw2UM",
    github: "https://github.com/Mo-khalifa2002/portofolio_project.git",
    img: "https://images.pexels.com/photos/8100514/pexels-photo-8100514.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    responsive: "responsive",
    title: "to-do app",
    demo: "https://mo-khalifa-todo-app.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/todo-reactjs-app.git",
    img: "https://images.pexels.com/photos/110473/pexels-photo-110473.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    responsive: null,
    title: "Movies - only focusing on react js",
    demo: "https://mo-khalifa-movies.netlify.app/",
    youtubeLink: "https://youtu.be/T2jzC3OzcIs",
    github: "https://github.com/Mo-khalifa2002/movies.git",
    img: "https://images.pexels.com/photos/65437/pexels-photo-65437.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 7,
    responsive: "not responsive",
    title: "portfolio landing page",
    demo: "https://mo-khalifa-landing-page.netlify.app/",
    youtubeLink: "https://youtu.be/hcyFQPDswt4",
    github: "https://github.com/Mo-khalifa2002/landing-page.git",
    img: "https://images.pexels.com/photos/159618/still-life-school-retro-ink-159618.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 8,
    responsive: "responsive",
    title: "budget calculator",
    demo: "https://mo-khalifa-budget-calculator.netlify.app/",
    youtubeLink: "https://youtu.be/QhMZRQK6oXA",
    github: "https://github.com/Mo-khalifa2002/budget-calculator.git",
    img: "https://images.pexels.com/photos/220301/pexels-photo-220301.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 15,
    responsive: "responsive",
    title: "learning MUI",
    demo: "https://mo-khalifa-first-mui-project.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/learnMui.git",
    img: "https://images.pexels.com/photos/326502/pexels-photo-326502.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    id: 9,
    responsive: "responsive",
    title: "color generator",
    demo: "https://mo-khalifa-color-generator-small.netlify.app",
    youtubeLink: "https://youtu.be/m32nH7HJjoo",
    github: "https://github.com/Mo-khalifa2002/budget-calculator.git",
    img: "https://images.pexels.com/photos/891030/pexels-photo-891030.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 10,
    responsive: "responsive",
    title: "small movie filtering",
    demo: "https://mo-khalifa-movie-filtering.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/movies-filtering.git",
    img: "https://images.pexels.com/photos/269140/pexels-photo-269140.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 11,
    responsive: "responsive",
    title: "e-commerce 3:55 to 4:53",
    demo: "https://mo-khalifa-movie-filtering.netlify.app/",
    youtubeLink: "https://youtu.be/ir4Q48CF6dk",
    github: null,
    img: "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 12,
    responsive: "responsive",
    title: "mobile weather app",
    demo: "https://mo-khalifa-mobile-weather-app.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/weather.git",
    img: "https://images.pexels.com/photos/209831/pexels-photo-209831.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 13,
    responsive: "responsive",
    title: "simple pure cart app",
    demo: "https://mo-khalifa-simple-shopping-cart-react.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/simple-react-shopping-cart.git",
    img: "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 14,
    responsive: "responsive",
    title: "tabs - small react js project",
    demo: "https://mo-khalifa-tabs-small.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/tabs-small.git",
    img: "https://images.pexels.com/photos/7864533/pexels-photo-7864533.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 16,
    responsive: "responsive",
    title: "small accordion",
    demo: "https://mo-khalifa-accordion-small.netlify.app/",
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/accordion-small.git",
    img: "https://images.pexels.com/photos/163823/accordion-musical-instrument-handzuginstrument-musician-163823.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 17,
    responsive: "responsive",
    title: "small birthday reminder",
    demo: null,
    youtubeLink: null,
    github: "https://github.com/Mo-khalifa2002/accordion-small.git",
    img: "https://images.pexels.com/photos/1543762/pexels-photo-1543762.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];